### ISSUE TITLE
Pseudonymisation: Exception if encounter with more than one Encounter.diagnosis

### ISSUE THREAD

**Issue by Mandalka** [juliangruendner/pj7-data-extraction#4]
Exception if encounter with more than one `Encounter.diagnosis`:

```
Traceback (most recent call last):
  File "pseudonymisation.py", line 369, in <module>
    psd_list = pseudonomise_resources(input_list, psd_config)
  File "pseudonymisation.py", line 342, in pseudonomise_resources
    psd_resources.append(pseudonomise_resource(resource, psd_config))
  File "pseudonymisation.py", line 317, in pseudonomise_resource
    change_id_in_obj_by_expression_simple(
  File "pseudonymisation.py", line 145, in change_id_in_obj_by_expression_simple
    change_id_in_obj_by_expression_simple(path, id_change, resource)
  File "pseudonymisation.py", line 138, in change_id_in_obj_by_expression_simple
    change_id_in_obj_by_expression_simple(path, id_change, arr_entry)
  File "pseudonymisation.py", line 113, in change_id_in_obj_by_expression_simple
    cur_key = path.pop(0)
IndexError: pop from empty list
```

while call of change_id_in_obj_by_expression_simple() with parameters "path" []
 "id_change" {'id_pool': 'cond_id_pseudonyms', 'id_prefix': 'Condition/', 'path_to_id': 'diagnosis.[*].condition.reference'}
and "resouce" {}

Example `enc.json` (only the part causing this exception; deleted diagnosis.use, diagnosis.rank and other elements):

```

[
  {
    "diagnosis": [
      {
        "condition": {
          "reference": "Condition/firstconditionid"
        }
      },
      {
        "condition": {
          "reference": "Condition/otherconditionid"
        }
      }
    ],
    "resourceType": "Encounter",
    "id": "myencounterid"
  } 
]

```

**Comment by juliangruendner** [comment]
@Mandalka fixed in version 0.6.2
